name: Deploy storybook with chromatic
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  chromatic-deployment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn

        # Build and Deploy storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true

  output-storybook-url:
    if: ${{ github.event_name == 'pull_request' }}
    needs: chromatic-deployment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get last commit hash
        uses: nrwl/last-successful-commit-action@v1
        id: last_successful_commit
        with:
          branch: ${{github.head_ref}}
          workflow_id: "chromatic.yml"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Hash
        run: echo "${{ steps.last_successful_commit.outputs.commit_hash }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### chromatic
            ### Storybook deployed successfully 🚀🚀 🎉 🎉
            See the latest storybook changes for this PR [here](https://${{ steps.last_successful_commit.outputs.commit_hash }}--${{secrets.STORYBOOK_DOMAIN}})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
