name: Deploy storybook with chromatic
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  chromatic-deployment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn

        # Build and Deploy storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true

  output-storybook-url:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x"]
        os: [ubuntu-latest]
    steps:
      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Check Hash
        run: echo "${{ env.hash }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### chromatic
            ### Storybook deployed successfully 🚀🚀 🎉 🎉
            See the latest storybook changes for this PR [here](https://${{ env.hash }}--${{secrets.STORYBOOK_DOMAIN}})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
